version: "3.9"
services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
  
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
